# -*- coding: utf-8 -*-
{
    'name': 'Licenses: Theme Adds Clarico',
    'version': '10.0.1.0.0',
    'summary': 'Tema addicional para Clarico Theme',
    'description': 'Modifica y adapta el tema Clarico Theme a las necesidades del sitio web',
    'author': 'Comunitea',
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    'category': 'Custom',
    'contributors': [
        "Ruben Seijas <ruben@comunitea.com>",
        "Pavel Smirnov <pavel@comunitea.com>"
    ],
    'depends': [
        # General
        'website_sale',
        'website_portal',
        'website_cookie_notice',
        'website_product_tags_73lines',
        'website_crm_recaptcha',
        'website_mail_channel',
        'payment',
        'payment_redsys',
        'payment_paypal',
        'website_sale_one_step_checkout_delivery',
        # 'website_sale_require_legal',
        # 'website_canonical_url',
        'website_sale_require_login',
        'website_crm_privacy_policy',
        'sgeede_infinite_scroll',
        'theme_clarico',
        # Custom
        'checkout_coupon',
        'google_tag_manager',
        'facebook_pixel_manager',
        'payment_paga_mas_tarde',
        'payment_cash_on_delivery',
        'payment_acquirer_by_amount',
        'website_sale_filter_countries',
        'website_sale_one_step_checkout_charge_payment_fee',
        'doofinder_search',
        'google_merchant_export',
        'revi_reviews',
        # 'seo_base',
    ],
    'data': [
        'data/redsys.xml',
        'data/product_data.xml',
        'views/cart.xml',
        'views/product.xml',
        'views/wishlist.xml',
        'views/blog.xml',
        'views/pages.xml',
        'views/menu.xml',
        'views/shop_home.xml',
        'views/contactus.xml',
        'views/footer.xml',
        'views/header.xml',
        'views/views.xml',
        'views/product_view.xml',
        'views/res_partner_view.xml',
        'views/payment_view.xml',
        'views/account.xml',
        'views/group.xml',
        'views/terms.xml',
        # 'views/category_view.xml',
        'views/robots.xml',
        'views/sitemap.xml',
        'views/payment.xml',
        'views/delivery_view.xml',
        'views/sale_order_view.xml'
    ],
    'qweb': [
    ],
    'installable': True,
    'application': True,
}
